/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.travel;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.event.TableModelEvent;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailsFrame = new javax.swing.JFrame();
        title = new javax.swing.JLabel();
        intro = new javax.swing.JLabel();
        content = new javax.swing.JScrollPane();
        contentTextPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        loginDialog = new javax.swing.JDialog();
        loginPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();
        addDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        introLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        contentLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        introField = new javax.swing.JTextField();
        imageField = new javax.swing.JTextField();
        contentField = new javax.swing.JTextField();
        addDlgBtn = new javax.swing.JButton();
        guidePanel = new javax.swing.JPanel();
        guideScrollPanel = new javax.swing.JScrollPane();
        guideTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new java.awt.Button();
        rmBtn = new java.awt.Button();
        adminMenuBar = new javax.swing.JMenuBar();
        adminMenu = new javax.swing.JMenu();

        detailsFrame.setMinimumSize(new java.awt.Dimension(700, 500));

        title.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        title.setText("Title");

        intro.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        intro.setText("Intro");

        contentTextPane.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        contentTextPane.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        content.setViewportView(contentTextPane);

        javax.swing.GroupLayout detailsFrameLayout = new javax.swing.GroupLayout(detailsFrame.getContentPane());
        detailsFrame.getContentPane().setLayout(detailsFrameLayout);
        detailsFrameLayout.setHorizontalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content)
                    .addGroup(detailsFrameLayout.createSequentialGroup()
                        .addGroup(detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intro)
                            .addComponent(title))
                        .addGap(0, 506, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailsFrameLayout.setVerticalGroup(
            detailsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loginDialog.setAlwaysOnTop(true);
        loginDialog.setMinimumSize(new java.awt.Dimension(250, 170));
        loginDialog.setModal(true);
        loginDialog.setResizable(false);
        loginDialog.setSize(new java.awt.Dimension(250, 200));

        loginPanel.setMaximumSize(null);

        loginLabel.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        loginLabel.setText("Admin Login");
        loginLabel.setToolTipText("");

        userField.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        passField.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N

        LoginBtn.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnClicked(evt);
            }
        });

        errorMsg.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userField)
                    .addComponent(passField)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(LoginBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        addDialog.setTitle("Add Data");
        addDialog.setMinimumSize(new java.awt.Dimension(500, 300));
        addDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        titleLabel.setText("Title");

        introLabel.setText("Intro");

        imgLabel.setText("Image");

        contentLabel.setText("Content");

        titleField.setText("title");

        introField.setText("intro");

        imageField.setText("image");

        contentField.setText("content");

        addDlgBtn.setText("Add");
        addDlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDlgBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLabel)
                            .addComponent(contentLabel)
                            .addComponent(titleLabel)
                            .addComponent(introLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contentField, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(imageField)
                            .addComponent(introField)
                            .addComponent(titleField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addDlgBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introLabel)
                    .addComponent(introField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imgLabel)
                    .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contentLabel)
                    .addComponent(contentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDlgBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel Guide System");
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        guidePanel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        guidePanel.setMinimumSize(new java.awt.Dimension(500, 250));

        guideTable.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        guideTable.setModel(getGuides());
        guideTable.setShowVerticalLines(false);
        guideTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClickHandler(evt);
            }
        });
        guideScrollPanel.setViewportView(guideTable);

        addBtn.setEnabled(false);
        addBtn.setLabel("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        rmBtn.setEnabled(false);
        rmBtn.setLabel("Remove");
        rmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout guidePanelLayout = new javax.swing.GroupLayout(guidePanel);
        guidePanel.setLayout(guidePanelLayout);
        guidePanelLayout.setHorizontalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guideScrollPanel)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        guidePanelLayout.setVerticalGroup(
            guidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guideScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(guidePanel, "card2");

        adminMenu.setText("Admin");
        adminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMenuMouseClicked(evt);
            }
        });
        adminMenuBar.add(adminMenu);

        setJMenuBar(adminMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClickHandler
        int row = guideTable.getSelectedRow();
        if (evt.getClickCount() == 2 && row != -1) {
            String id = (String) guideTable.getModel().getValueAt(row, 0);
            Guide guide = DbHelper.getGuideById(id);
            detailsFrame.show();
            title.setText(guide.getTitle());
            intro.setText(guide.getIntro());
            contentTextPane.setText(guide.getContent());
            contentTextPane.setEditable(false);
            String path = guide.getImg();
            URL url;
            try {
                url = new URL(path);
                BufferedImage image = ImageIO.read(url);
                jLabel1.setIcon(new ImageIcon(image));
            } catch (MalformedURLException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tableClickHandler

    private void adminMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseClicked
        if (adminMenu.isEnabled()) {
            loginDialog.show();
        }
    }//GEN-LAST:event_adminMenuMouseClicked

    private void loginBtnClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnClicked
        if (("admin".equals(userField.getText())) && ("admin".equals(String.valueOf(passField.getPassword())))) {
            loginDialog.hide();
            activateAdmin();
        } else {
            errorMsg.setText("Error");
            userField.setText("");
            passField.setText("");
        }
    }//GEN-LAST:event_loginBtnClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        addDialog.show();
    }//GEN-LAST:event_addBtnMouseClicked

    private void addDlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDlgBtnActionPerformed
        Guide guide = new Guide();
        guide.setTitle(titleField.getText());
        guide.setIntro(introField.getText());
        guide.setImg(imageField.getText());
        guide.setContent(contentField.getText());
        int id = DbHelper.addTable(guide);
        guideTable.setModel(getGuides());
        addDialog.setVisible(false);
    }//GEN-LAST:event_addDlgBtnActionPerformed

    private void rmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmBtnActionPerformed
        int row = guideTable.getSelectedRow();
        String id = (String) guideTable.getModel().getValueAt(row, 0);
        DbHelper.deleteTable(id);
        guideTable.setModel(getGuides());
    }//GEN-LAST:event_rmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    private static TableModel getGuides() {
        List<Guide> guideObj = DbHelper.getGuide();
        Object[][] guidesArr = new String[guideObj.size()][3];
        for (int i = 0; i < guideObj.size(); i++) {
            guidesArr[i][0] = Integer.toString(guideObj.get(i).getId());
            guidesArr[i][1] = guideObj.get(i).getTitle();
            guidesArr[i][2] = guideObj.get(i).getIntro();
        }
        AbstractTableModel tableModel;
        tableModel = new AbstractTableModel() {
            private String[] columnName = {"Id", "Title", "Intro"};
            private Object[][] data = guidesArr;

            @Override
            public void fireTableDataChanged() {
                super.fireTableDataChanged();
            }

            @Override
            public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
                String id = (String) getValueAt(rowIndex, 0);
                Guide guide = DbHelper.getGuideById(id);
                switch (columnIndex) {
                    case 1:
                        guide.setTitle((String) aValue);
                        break;
                    case 2:
                        guide.setIntro((String) aValue);
                        break;
                }
                DbHelper.updateTable(guide);
                data[rowIndex][columnIndex] = aValue;
            }

            @Override
            public String getColumnName(int column) {
                return columnName[column];
            }

            @Override
            public int getRowCount() {
                return data.length;
            }

            @Override
            public int getColumnCount() {
                return columnName.length;
            }

            @Override
            public Object getValueAt(int rowIndex, int columnIndex) {
                return data[rowIndex][columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int col) {
                switch (col) {
                    case 0:
                        return false;
                    default:
                        return isAdmin;
                }
            }
        };
        return tableModel;
    }

    private void activateAdmin() {
        isAdmin = true;
        addBtn.setEnabled(true);
        rmBtn.setEnabled(true);
        adminMenu.setEnabled(false);
    }

    private static boolean isAdmin = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private java.awt.Button addBtn;
    private javax.swing.JDialog addDialog;
    private javax.swing.JButton addDlgBtn;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuBar adminMenuBar;
    private javax.swing.JScrollPane content;
    private javax.swing.JTextField contentField;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JTextPane contentTextPane;
    private javax.swing.JFrame detailsFrame;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JPanel guidePanel;
    private javax.swing.JScrollPane guideScrollPanel;
    private javax.swing.JTable guideTable;
    private javax.swing.JTextField imageField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel intro;
    private javax.swing.JTextField introField;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passField;
    private java.awt.Button rmBtn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
